services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-service
    env_file:
      - .env
    volumes:
    - ./mysql-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - mysql-service
    ports:
      - "8001:8001"

  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - mysql-service
    ports:
      - "8002:8002"

  gateway:
    build: ./gateway
    container_name: gateway
    env_file:
      - ./gateway/.env
    ports:
      - "8000:8000"

  account-service:
    build: ./account-service    
    container_name: account-service
    env_file:
      - ./account-service/.env
    depends_on:
      - mysql-service
    ports:
      - "8003:8003"

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    env_file:
      - ./transaction-service/.env
    depends_on:
      - mysql-service
    ports:
      - "8004:8004"

  
  dashboard-service:
    build: ./dashboard-service
    container_name: dashboard-service
    env_file:
      - ./dashboard-service/.env
    depends_on:
      - mysql-service
    ports:
      - "8005:8005"